#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
git diff --cached --name-status | while read x file; do
  for disallowed in .env pre-commit commit-msg
  do 
    echo $disallowed
    if [ "$disallowed" == "$file" ]; then
		  echo "ERROR: This commit contains disallowed file: \"${disallowed}\""
		  exit 1
	  fi
  done
done || exit $?
